#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/example"

remove_action() {
    # Activate trigger to purge cached files.
    dpkg-trigger update-fixperms
}

case "$1" in
    remove)
        remove_action
    ;;

    purge)
        remove_action
        if omv_config_exists ${CONFIG}; then
            echo "Deleting Configuration"
            omv_config_delete ${CONFIG};
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
