#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        chown root:root /bin/get_hdparm
        chmod 4755 /bin/get_hdparm

        # reload override file
        systemctl daemon-reload

        # Activate package triggers.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."

        omv-confdbadm create "conf.service.drivemon"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.drivemon" "${2}"
        fi
    ;;

abort-upgrade|abort-remove|abort-deconfigure)
    ;;

*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
